name: Vitalog
values:
  - key: baseUrl
    value: http://localhost:3000
    enabled: true
  - key: authKey
    value: ""
    type: secret
    enabled: true
  - key: rootAuthKey
    value: ""
    type: secret
    enabled: true
  - key: rootEmail
    value: ""
    type: secret
    enabled: true
  - key: rootPassword
    value: ""
    type: secret
    enabled: true
  - key: oauthCode
    value: ""
    type: secret
    enabled: true
  - key: oauthVerifier
    value: ""
    type: secret
    enabled: true
  - key: oauthCsrf
    value: ""
    type: secret
    enabled: true
  - key: oauthChallenge
    value: ""
    enabled: true
  - key: oauthState
    value: ""
    enabled: true
