name: Vitalog
values:
  - key: baseUrl
    value: http://localhost:3000
    enabled: true
  - key: authKey
    value: ""
    type: secret
    enabled: true
  - key: rootAuthKey
    value: ""
    type: secret
    enabled: true
  - key: rootEmail
    value: ""
    type: secret
    enabled: true
  - key: rootPassword
    value: ""
    type: secret
    enabled: true
